fix build on linux
JanosGit/PluginBase pull request #1
Opened 2022-04-28 22:59 UTC by BillyDM

This seems to fix the build issue I was having mentioned in the issue https://github.com/JanosGit/Schrammel_OJD/issues/40

The build of Schrammel_OJD still fails overall with this error, but at-least this part of the problem is fixed.

```
/usr/bin/ld: BinaryResources/libEmbeddedBinaryData.a(BinaryData1.cpp.o): warning: relocation against `_ZN10BinaryData8knob_svgE' in read-only section `.text'
/usr/bin/ld: libjb_git_version-OJD-VST3.a(gitVersion.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN11ProjectInfo3Git3tagB5cxx11E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/OJD-VST3_VST3.dir/build.make:247: OJD-VST3_artefacts/Release/VST3/OJD.vst3/Contents/x86_64-linux/OJD.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:307: CMakeFiles/OJD-VST3_VST3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

2022-04-29 08:48 UTC, JanosGit requested changes
Thanks for your contribution. The changes look sensible so far, but I care about code style a lot, so would you mind reformatting the code so that it follows the [JUCE coding standards](https://juce.com/discover/stories/coding-standards) that this project roughly follows? 

In this case especially put a whitespace before non-empty braces.

Thank you

2022-04-29 08:50 UTC, JanosGit commented on jb_plugin_base/Utils/MessageOfTheDay.h
> +                    int generalMessageVersion = static_cast<juce::int64>(general.getProperty ("Version", static_cast<juce::int64>(lastVersion)));
while you are at it, this could be changed to `int64_t generalMessageVersion` to be consistent with the block above – don't see any obvious reason why I chosed `int` here

2022-04-29 08:59 UTC, JanosGit commented
Regarding the linker warning, this has to be fixed in the OJD project. 

Could you try adding this at the OJDs CMakeLists in Line 88

```
if (UNIX AND NOT APPLE )
    set_target_properties (OJD-${format} 
        PROPERTIES
            POSITION_INDEPENDENT_CODE TRUE)
endif()
```

In case this fixes the error, feel free to create another PR over there that adds this and updates the PluginBase submodule to the latest fixes contributed here.

2022-04-29 16:50 UTC, JanosGit approved these changes

2022-04-29 16:53 UTC, merged

2022-04-29 17:20 UTC, BillyDM commented
> Could you try adding this at the OJDs CMakeLists in Line 88

After adding it, I get this error when running `cmake -DCMAKE_BUILD_TYPE=Release -B build`
```
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'alsa'
--   Found alsa, version 1.2.6.1
-- Checking for module 'freetype2'
--   Found freetype2, version 24.2.18
-- Checking for module 'libcurl'
--   Found libcurl, version 7.82.0
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
--   Found webkit2gtk-4.0, version 2.36.0
--   Found gtk+-x11-3.0, version 3.24.33
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
-- Using the single-header code from /home/billydm/Dev/Schrammel_OJD/Ext/JBPluginBase/Ext/json/single_include/
-- Configuring done
CMake Error at Ext/JUCE/extras/Build/CMake/JUCEUtils.cmake:1642 (add_library):
  Target "OJD-VST3" links to itself.
Call Stack (most recent call first):
  CMakeLists.txt:53 (juce_add_plugin)
  CMakeLists.txt:113 (add_ojd_version)


CMake Error at Ext/JUCE/extras/Build/CMake/JUCEUtils.cmake:1642 (add_library):
  Target "OJD-VST3" links to itself.
Call Stack (most recent call first):
  CMakeLists.txt:53 (juce_add_plugin)
  CMakeLists.txt:113 (add_ojd_version)


CMake Error at Ext/JUCE/extras/Build/CMake/JUCEUtils.cmake:1642 (add_library):
  Target "OJD-VST3" links to itself.
Call Stack (most recent call first):
  CMakeLists.txt:53 (juce_add_plugin)
  CMakeLists.txt:113 (add_ojd_version)

```

2022-04-29 17:40 UTC, JanosGit commented
Thanks for trying that. Unfortunately I don’t have an idea what could trigger the error you are seeing now. Could you share the edited CMakeLists as a whole?

2022-04-29 23:05 UTC, BillyDM commented
> Could you share the edited CMakeLists as a whole?
[CMakeLists.txt](https://github.com/JanosGit/PluginBase/files/8595168/CMakeLists.txt)

2022-05-03 20:28 UTC, JanosGit commented
Sorry for the late reply. Seems like I was a bit unclear, you added the proposed change in line 88 of the CMakeLists on the master branch while I was referring to the develop branch. You might want to try that again with the develop branch ;)

In any case, I try to set up a GitHub Actions based Linux build in addition to the existing Windows and Mac builds soon, but I cannot give an exact estimate when that will happen

2022-05-09 21:00 UTC, JanosGit commented
@BillyDM I pushed some changes to this branch [15-add-a-linux-build](https://github.com/JanosGit/Schrammel_OJD/tree/15-add-a-linux-build).

This is still work in progress, especially there are a lot of compile warnings that I need to silence, but I just got a successful Ubuntu build on GitHub Actions. Would you mind trying if pulling that branch solves your problems?